### ISSUE TITLE
Streams - suggestions

### ISSUE THREAD

**Issue by ph4r05** [crocs-muni/CryptoStreams#20]
Hi,

I was wondering what is the maintainers' opinion about the following possible stream types (may be already on your roadmap, discussed previously or already doable by another streams & configuration):

### Low Hamming weight 
Generate stream with low hamming weight. E.g., 1bit vectors, 2bit, etc. Could useful for I/O analysis of the ciphers. May reveal some new weaknesses when analyzing long output sequences.
The extended version could start with random first vector, then XOR the low hamming weight stream.

### Gradual SAC
The idea is to get a long output sequence. It could work similarly to `sac-2d-all-positions` but after depleting the all potential positions the first vector could be slightly mutated. E.g., XOR with low hamming weight vector - using previous method. Then apply `sac-2d-all-positions` again. In this way we can get input block very similar to each other and slightly evolving. This can be also useful for long output sequence analysis.

### Rho
Simple, maybe useful. Function-dependent. Output of the function is taken as an input to the next invocation. Not sure if this is possible at the moment.

### LUT
@sysox 's random number generator with parametrizable randomness. Could be also nice to study the behaviour of the analyzed function in long streams. 

EDIT1:

### Distribution sampling
Another variant of non-random input. Inputs could be sampled from some specific distributions which could be then looked for in the function outputs. 

Thanks for feedback!

**Comment by ph4r05** [comment]
Note: I am currently implementing Hamming weight counter stream to the project.

**Comment by ph4r05** [comment]
### Repeat stream
Repeats underlying stream given number of times. Would generalize key / iv reinitialization. 
Repeat(HW_ctr, 1000) is equivalent to repeating 1000 times first value from HW_ctr, then calling `HW_ctr->next()`, again 1000 times the same value...

**Comment by mitko501** [comment]
I don't see any problem with any of these you mentioned. Except, I don't understand what you mean by Distribution sampling. What do you mean by looking for non-random distribution in functions output?

**Comment by ph4r05** [comment]
@mitko501 distribution sampling - I mean e.g. gauss, poison, just an idea :)

**Comment by Bender250** [comment]
https://github.com/ph4r05/eacirc-streams/commit/ae184bc1e68377f97b0c3c0096c44b839cb937bc

Rho added.

I also created `repeating_stream` and I use it iternally to modify "projects" (complex stream with lot of capabilities - `repeating_stream` will simplify at least estream a little bit).

**Comment by Bender250** [comment]
Rho accepted: https://github.com/crocs-muni/CryptoStreams/pull/53

I am going to write distribution sampling and then we can close this issue. LUT is rejected/postponed by Petr unless Syso would find time to finish it and maybe publish it...

**Comment by Bender250** [comment]
Implemented 5 distribution sampling methods from http://en.cppreference.com/w/cpp/numeric/random in https://github.com/crocs-muni/CryptoStreams/tree/distribution_sampling_streams.

bernoulli-distribution
binomial-distribution
normal-distribution
poisson-distribution
exponential-distribution

**Comment by Bender250** [comment]
https://github.com/crocs-muni/CryptoStreams/pull/65
