### ISSUE TITLE
Implement other hash functions and ciphers

### ISSUE THREAD

**Issue by Bender250** [crocs-muni/CryptoStreams#29]
_Migrated from https://github.com/crocs-muni/eacirc/issues/49_

Implement those functions:
 * SHA-1, SHA-2, MD5
 * MARS, RC6, Serpent
 * Maybe A5/1, A5/2, Kasumi, IDEA, Streebog

After implementing them, document them in the wiki.

@rozsa117

**Comment by ph4r05** [comment]
I've already implemented IDEA (its in the blog).

**Comment by Bender250** [comment]
Same for MARS, RC6, Serpent and Twofish.

Also all the implemented functions are already in wiki.

**Comment by Bender250** [comment]
A5/1, A5/2, Streebog moved to https://github.com/crocs-muni/CryptoStreams/issues/51.

Others are done.
