### ISSUE TITLE
Analyze licences of included functions to stay with MIT/BSD-like

### ISSUE THREAD

**Issue by petrs** [crocs-muni/CryptoStreams#45]

**Comment by Bender250** [comment]
I found these licenses:

* [OpenSSL in CAESAR](https://github.com/crocs-muni/CryptoStreams/blob/3754e134304a8d232a9322dc8a5d6695772e36a0/streams/caesar/aead/omd/omdsha256k128n96tau128v1/omdsha256k128n96tau128v1_sha256.h), [2](https://github.com/crocs-muni/CryptoStreams/blob/3754e134304a8d232a9322dc8a5d6695772e36a0/streams/caesar/aead/omd/omdsha256k256n248tau256v1/omdsha256k256n248tau256v1_sha256.cpp)...
* [GNU GPL almost everywhere in CAESAR](https://github.com/crocs-muni/CryptoStreams/search?utf8=%E2%9C%93&q=GNU&type=)
* [Simplified BSD in Botan code (@rozsa117 commits)](https://github.com/crocs-muni/CryptoStreams/blob/14d8720f07531bb4aeaff8745679254685633447/streams/block/ciphers/kasumi/kasumi.h)
* [MIT](https://github.com/crocs-muni/CryptoStreams/blob/25de00081418995e63fd28a31a9a9c5550040844/streams/block/ciphers/speck/speck.cpp)
* [SPDX-License-Identifier: Apache-2.0](https://github.com/crocs-muni/CryptoStreams/blob/9813e57c5c86966a692a8015e2f6f38a6a94c286/streams/block/ciphers/camellia/camellia.cpp)
* Others:
  - [what?](https://github.com/crocs-muni/CryptoStreams/blob/3754e134304a8d232a9322dc8a5d6695772e36a0/streams/caesar/aead/silc/present80n6silcv1/present80n6silcv1_present.cpp)
  - [ok](https://github.com/crocs-muni/CryptoStreams/blob/3754e134304a8d232a9322dc8a5d6695772e36a0/streams/caesar/aead/aes-otr/aes128otrpv1/aes128otrpv1_t-aes_define.h)
  - [confidential property? :D](https://github.com/crocs-muni/CryptoStreams/blob/14314fc8f935ce8f0e786c54c0a406dbf3756861/streams/hash/sha3/hash_functions/Khichidi/common.h)
  - [release of binary = mentioning this licence](https://github.com/crocs-muni/CryptoStreams/blob/3754e134304a8d232a9322dc8a5d6695772e36a0/streams/caesar/aead/enchilada/enchilada256v1/enchilada256v1_aes.h)


Generally: CAESAR has plenty of licences, mostly GPL - it was probably up to authors. eSTREAM has none and SHA-3 has occasionally some MIT/BSD.

**Comment by Bender250** [comment]
https://github.com/crocs-muni/CryptoStreams/tree/license

I will try to remove the GPL. Only problem in this branch is just NaSHA and Skein SHA-3 candidates. NaSHA is forgotten code (dead website...), I would remove it, but Skein is finalist.

**Comment by Bender250** [comment]
[Community profile checklist: code of conduct, contributing and license added](https://github.com/crocs-muni/CryptoStreams/pull/70)

MIT license

**Comment by Bender250** [comment]
https://github.com/crocs-muni/CryptoStreams/pull/69
